### ISSUE TITLE
Selling items for full price

### ISSUE THREAD

**Issue by jlkoneczny** [tsmigiel/haven-helper#1]
Items are being sold for full price but should be sold for half price according to rules https://online.flippingbook.com/view/598058/43/

**Comment by tsmigiel** [comment]
Ahh, actually that was an intentional feature. I allow people to sell at full price until they actually play a scenario. Though, users can really do that themselves without the apps help, so I will just follow the rules to avoid confusion.

**Comment by tsmigiel** [comment]
Thanks for the report. Fixed.
