### ISSUE TITLE
Server error when trying to check box for players playing in setup

### ISSUE THREAD

**Issue by jlkoneczny** [tsmigiel/haven-helper#2]
The checkbox is not being checked when clicking on players in step 1 of setup. The console gives the message 
`server error: gh:server:change_setup [object Object] [globals.js:73](webpack://Main/dist/client/globals.js)` whenever the input box is clicked.

**Comment by jlkoneczny** [comment]
It would be nice to have the error message bubble up to the UI as a toast message or something to let me know something happened (even if it was an error). I saw there was a server error when trying to advance the scenario, but I assume it's related to no players being selected.

**Comment by tsmigiel** [comment]
Sorry, newbie error on my part. A bug with the ' characters in your character name.

**Comment by tsmigiel** [comment]
I fixed the bug, please try again.

I will work on improving the UI so the error is more obvious. Some kind of popup is a good idea.

**Comment by tsmigiel** [comment]
I created a separate issue  regarding making the errors nicer.
