### ISSUE TITLE
Bug in city event 15 option B, perk checkmarks

### ISSUE THREAD

**Issue by tsmigiel** [tsmigiel/haven-helper#20]
It is adjusting perk checkmarks incorrectly.

**Comment by JesusLopezCh** [comment]
Same happens for Road Event 21, Option A

![image](https://user-images.githubusercontent.com/7446271/162290038-19bc4d0e-ac7a-4e42-a9f1-8a8df458d2aa.png)

**Comment by JesusLopezCh** [comment]
I'm guessing this "Lose 1 Perk" function is used across all events, so not worth mentioning every Event that results in losing a Perk, right?, as they all are failing.

Adding another one just in Case:

Road Event 6, Option A
![image](https://user-images.githubusercontent.com/7446271/162291519-b711ba09-a878-4c9e-a538-43ca2b39f880.png)

**Comment by tsmigiel** [comment]
Yeah, you are right, they will all use the same code.

**Comment by tsmigiel** [comment]
Should be fixed now. And behave correctly so a player does not lose a perk.
