### ISSUE TITLE
Milestone Cards

### ISSUE THREAD

**Issue by benbaker100** [tsmigiel/haven-helper#23]
Do you have plans to add the [Crimson Scales milestone ability cards](https://imgur.com/a/vgQFvCo)? These cards are unlocked once a character completes their milestone goal. They are treated like level 1/X cards for enhancement purposes, but they count as spoilers until the goal is accomplished.

**Comment by tsmigiel** [comment]
Ahh, I had not noticed the milestones yet. I will add them and the corresponding cards from that link.

**Comment by tsmigiel** [comment]
I have added the milestone and related cards to the character edit screen. 

Thanks for reporting this. Please let me know if it could be better.

**Comment by benbaker100** [comment]
Thank you! When I mark the milestone as complete, the card shows up in my "available pool", but when I play a scenario it does not show up in my hand.

**Comment by tsmigiel** [comment]
Ahh, sorry, I missed that. It is there now.  On the Cards page you can click "Reload" to see it. It will also show up when you choose a new scenario.

**Comment by benbaker100** [comment]
There it is. Thanks again!
