### ISSUE TITLE
Monster / Summon AI Bug

### ISSUE THREAD

**Issue by jonathanmclaus** [tsmigiel/haven-helper#24]
Was recently using the app and the suggested route for a summon was incorrect.

![image](https://github.com/tsmigiel/gloomhaven-full-stack/assets/5731591/15dae931-6b11-4d74-a181-4581f51ed402)

Skeleton 5 is shown walking into a positive trap. However, it has a path to its focus that only requires traversing a single negative hex (including positive traps), so it would prioritize that and end its turn in the upper empty door hex.

**Comment by tsmigiel** [comment]
Thanks for letting me know. I hadn't even considered positive traps. :) I'll fix it.

**Comment by tsmigiel** [comment]
Oh, I didn't read closely enough. The fact that it is positive is not relevant, monsters will avoid positive traps the same way they avoid negative traps.

From that screen shot, isn't the only path through the ladder? Which will require 2 traps. That hex marked (a) is surrounded by walls, so a monster won't move there.

**Comment by tsmigiel** [comment]
Ahh, but it is a character summon, so it should move through its allies.

**Comment by tsmigiel** [comment]
How long ago did you encounter this? I haven't reproduced it yet. I tried reproducing it on the same map with the same figures and traps.

I actually made a fix for exactly this sort of case on Dec 9th. So if your case happened before that, I think it is already fixed.

**Comment by jonathanmclaus** [comment]
This was 2 weeks ago, so safe to withdraw in that case.

**Comment by tsmigiel** [comment]
Cool.  Thanks for reporting it and sending a screenshot!  User reports and my own campaigns are the main way I discover these issues. :)
