### ISSUE TITLE
Monster AI doesn't minimize ddistance

### ISSUE THREAD

**Issue by jonathanmclaus** [tsmigiel/haven-helper#25]
![image](https://github.com/tsmigiel/gloomhaven-full-stack/assets/5731591/adcc2d62-eea1-4317-a436-db01a372943e)

The Night Demon has movement 3 but only chooses to go (8,12). It can and should go to (7, 12) instead to minimize the distance to its focus.

**Comment by tsmigiel** [comment]
Ahh, thanks. I'll fix it.

**Comment by tsmigiel** [comment]
It should be fixed now.

Thanks for letting me know! Note that the icy terrain has not been tested well, so please double check anything around them and let me know if you find mistakes.
