### ISSUE TITLE
How to modify Enemy Modifier deck for Challenge?

### ISSUE THREAD

**Issue by Random-Stack-Random-Day** [tsmigiel/haven-helper#26]
There is a challenge card "Imitation" which wants you to take unlocked characters perk cards and put them into the modifier deck; is this unsupported or am I missing something for how to do this?

**Comment by tsmigiel** [comment]
Ahh, there is not a way to handle this right now. I will work on it, but it will probably take a couple of days.

**Comment by tsmigiel** [comment]
Thanks for reporting this. I have added an "Imitation" button to the Monster modifier deck edit popup (i.e., tap the icon at the top right of the monster deck discard pile). That button will allow you to choose one of the available classes and add the random cards to the deck. Or remove them.
