### ISSUE TITLE
Enhancements of non-persistent abilities on persistent actions are incorrectly priced.

### ISSUE THREAD

**Issue by jonathanmclaus** [tsmigiel/haven-helper#27]
The rulebook states:

> If the ability provides a persistent bonus, whether or not the action has a lost icon, triple the cost. This does not apply to summon stat enhancements.

For an ability like the heal on the Meteor's [Cooling](https://github.com/any2cards/worldhaven/blob/master/images/character-ability-cards/frosthaven/PY/fh-cooling.png), GHFS lists the base price as 90 (30 * 3). However, the ability does not provide a persistent bonus and therefore should not be tripled, despite the presence of the persistent icon.

I realize it's probably too much labor to go through every card and check whether the persistent actually applies, but I think a tooltip on the enhancement menu warning that the user might need to uncheck the persistent box would be helpful.

**Comment by tsmigiel** [comment]
Thanks, fixed.

I reviewed all of the FH cards with respect to that rule. i.e., every card with the persistent icon. There were a few more with the same mistake.

Interestingly, I did not find a single card in FH where that rule would apply. There are some in GH, but I have not added this FH data to the GH cards.
